### ISSUE TITLE
Devilsaur Trinket Issue

### ISSUE THREAD

**Issue by kw12xx** [Nixxen/TrinketMenu#11]
First off, LOVE this addon. Thank you so much for your time!
My issue is with the AutoQueue: I have a predetermined list that is saved for pvp and the order is insignia > shadow reflector > ice reflector > flame reflector >Blackhand's breadth. I DO NOT have the devilsaur trinket in ANY of my lists, however the addon auto-equips that trinket instead of the ice reflector. Specifically, i use my trinket (in or out of combat), the auto-queue will either pick shadow reflector next or the devilsaur trinket. 50-50 shot. Sometimes it will not equip the proper trinkets at all (dismounting with carrot on a stick equipped; sometimes it will keep the carrot equipped, even when leaving combat again.

Just wondering what I can do: everything worked great until about 3-4 days ago... no new addons although I do use itemrack in conjunction with trinketmenu.

![TM ERROR](https://user-images.githubusercontent.com/21109371/83783255-15236800-a65e-11ea-9078-03b6112866a8.png)

**Comment by Nixxen** [comment]
I also use Itemrack for the "mount" set (since I have full riding gear which TM doesn't support) and if both TM and IR has the mount event triggers on, they can clash, and things start bugging.

Regarding the Devilsaur trinket, could you make sure it's not set as priority?
If it IS set as priority, that trinket will be considered before any other in the queue, regardless of how you've set up the queue.

**Comment by kw12xx** [comment]
Can't find the mount trigger for TM, but it _shouldn't_ be on.. Pretty sure i disabled that.

Devilsaur hasn't even been customized - so no, its not set as a priority. Which makes this so confusing as the other night, i was literally incapable of changing the trinket. Even when auto-queue was disabled, it was still auto-equipping the devilsaur trinket... I'm so confused. Itemid buggy maybe?

Only thing I can think of to do is to leave the trinket in my bank, but it IS useful for the ap buff.... 



Ok, so, very sorry for bothering you, I disabled "enable auto queue" for ItemRack (leaving enable events still checked) and it used the correct trinkets and didn't equip the devilsaur trinket. Confusing why it would choose that one out of all of the trinkets in my bag, but I'm about to test in combat to see if that was the issue.

Yeah, seems fine now. I'm sorry for the trouble! I was going crazy for like a week trying to figure this out T_T

**Comment by Nixxen** [comment]
Haha, glad it's solved at least.
And it's no trouble at all. I try to help whenever I can :)
