### ISSUE TITLE
Frame Strata

### ISSUE THREAD

**Issue by PsiloCA** [Nixxen/TrinketMenu#12]
wondering if there is or could be an option to adjust the frame strata of the trinket menus they seem to be set at a higher level than the boxes that show the actuall current equipped trinkets. this makes the trinket menu stand out on top of the character pane. and the main trinket window underneath it.

**Comment by PsiloCA** [comment]
![trinketmenustrata](https://user-images.githubusercontent.com/53628445/85167555-dbd22700-b21d-11ea-8049-28c6391cd2a2.jpg)

**Comment by Nixxen** [comment]
This is definitely doable, though adding it as an option would take more time. Hardcoding it significantly less, but could cause issues with other frames.
I've skimmed through the code and currently the addon is using the default strata that it's been assigned by wow it seems.
There is however 1 increment in frame level for any "sub menu" (i.e. popup trinket menus and such).

Do you want both frames to be behind the character frame, or both in front?

I suppose I could set any popups to be equal to the parent frame level, though that could cause some graphical issues in some edge cases.

(Just as a disclaimer, I'm very busy lately so might not get a chance to look at this in more depth until after summer or fall),

**Comment by PsiloCA** [comment]
its ok bud i always appreciate hearing back from a dedicated creator if setting the option isnt possible in game by the player then having both behind the char frame, in my opinion, would be best!

**Comment by PsiloCA** [comment]
i had a look thru the code. in the past i have been able to make changes like this but my overall understanding of LUA is minimal. 'if its easy'(easy is very subjective of course) i am happy to make some of the changes myself if you can point me to the section and line this particular setting is on.

**Comment by Nixxen** [comment]
The simplest:
In TrinketMenu.lua, all the references to "SetFrameLevel(n)" will affect the "depth" of the frame.
Changing all the ones where n is 2 to 1 will set them to the same level (since the rest are already at 1).
There's ways to have them mimic their "parent" frame, but don't worry about that for now :p 

Let me know if it works out with the character frame.

**Comment by PsiloCA** [comment]
I gave it a shot. tried all nums from 1 to 2, tried changing them all to 2. must be doing something wrong as its still the same. i made sure everything was saved and named correctly. what could i be missing?

**Comment by Nixxen** [comment]
Lower "SetFrameLevel" would be "further back" in the layering - so to speak.
I'm not sure what strata or level the character frame is though.
In this case however, you'd want them all to be set to 1, since that is the level of the "parent" frame, and that seems to play nice with the character frame.

By default wow handles frame level of "child" frames as "parentframelevel +1", so if there's a frame that's NOT defined by SetFrameLevel(1), that frame will still get 2 - which is unavoidable unless specifically forced to 1.

edit:
In case my explanation was bad, this might help:
https://wow.gamepedia.com/API_Frame_SetFrameLevel

**Comment by PsiloCA** [comment]
ok gonna give it another shot shortly, will let you know how it goes.

**Comment by PsiloCA** [comment]
the changes are only within the "trinketmenu.lua" file correct? nothing in the "trinketmenuopt.lua" or "trinketmenuqueue.lua" needs editing is that right?

**Comment by PsiloCA** [comment]
k well i did what you suggeested. setframelevel is all set to 1. but it doesnt appear to have fixed the issue i was having.

**Comment by PsiloCA** [comment]
ok i got it! turns out its not the lua file but in the xml file and changing frame strata from 'overlay' to 'high' adjusting those numbers in the lua didnt do anything. i tried many numbers too all the way up to 5.

**Comment by Nixxen** [comment]
Excellent!
So just for a note of clarification for mysel when I look at this later:
Setting the strata in the XML file from "overlay" to "high" gave you the wanted outcome of having the TM frame and popup frame always appear behind the character frame?

**Comment by PsiloCA** [comment]
yes that is correct. if you want i can get you the very specific lines or send you my updated xml file.

**Comment by PsiloCA** [comment]
trinketmenu.xml 
line 72 (frameStrata = "BACKGROUND") changed to (frameStrata = "OVERLAY")

line 185 (frameStrata = "HIGH") changed to (frameStrata = "OVERLAY")

So i think its just those two that affect the frame stratas, suppose you could change those two things to whatever you want. should it need to be 'ontop' of everything. 

attached is the trinketmenu.xml that provides me the results i wanted. hope this helps. again i appreciate you keeping this addon up to date and working! not to mention the response from you regarding any issue is impressive. TY!

enclosed in this zip file is the trinketmenu.xml file that has these changes already done if that helps.

[TrinketMenu.zip](https://github.com/Nixxen/TrinketMenu/files/4913937/TrinketMenu.zip)

**Comment by PsiloCA** [comment]
one of my original comments said changing the strata from 'OVERLAY' to 'HIGH'. this is backwards. for what i needed i changed the stratas all TO 'OVERLAY'

**Comment by PsiloCA** [comment]
Issued Closed! glad we got this figured out. addon improved one more notch! thanks for all your good works and keeping the addon community alive.
