### ISSUE TITLE
Spells in Trinket Menu

### ISSUE THREAD

**Issue by h3xp** [Nixxen/TrinketMenu#4]
Hey I would like to have an addon just as Trinket Menu but for spells,. So Instead of Trinkets I select spells, would it be a lot of effort to add that future to Trinket Menu or to tinker a similar addon out of this?

**Comment by Nixxen** [comment]
This is out of the scope of this particular project, but in theory - as long as every activation is triggered by a user keypress I don't see why it wouldn't work.

It would probably require a spell database/library lookup and a significant rewrite though.
