### ISSUE TITLE
Quick selection omission

### ISSUE THREAD

**Issue by VictAlucard** [Nixxen/TrinketMenu#6]
I'm not sure why or hot it began. some trinkets will not display when I mouseover. I have to open inventory or character pane to quickly select rather than using the built in quick select. example. I was able to swap to AV trinket for some time, then it randomly stops displaying in quick selection. Now, my blackhads breadth wont show in quick select? The trinket will display in the queu and It will queu as normal, however. It wont show if I want to manually switch? whereas other trinkets will. I'm not sure how to do a full data purge of this addon but i've removed the folder several times and updates with 13.2.4 as the addons says 13.2.2. Kindly advise?
![trinket](https://user-images.githubusercontent.com/62710885/77665770-7a6c2600-6f56-11ea-8d46-51e3f8024766.PNG)
![trinket2](https://user-images.githubusercontent.com/62710885/77665773-7b04bc80-6f56-11ea-97f2-5fe118cae8ca.PNG)
![trinket3](https://user-images.githubusercontent.com/62710885/77665874-9d96d580-6f56-11ea-8193-4e605d9f714d.PNG)

**Comment by Nixxen** [comment]
Regarding the trinkets disappearing issue:
I have not seen trinkets not displaying before. Is this happening permanently (As in it's never there any more), from time to time (as in it's there, then suddenly disappears) or just rarely (as in whenever you do a specific action in game).
Could it be related to number of trinkets?
I don't have as many trinkets as you, so won't be able to troubleshoot from my client. Try removing some of the other trinkets (put them in your bank), then do /reload and see if the missing ones appear back in the manual selection. 

To completely purge this addons data, delete the file "TrinketMenu.lua" in your accounts and characters "SavedVariables" folder.
These folders are located in 
`<wow install path>\_classic_\WTF\Account\<accountname>\SavedVariables\`
and
`<wow install path>\_classic_\WTF\Account\<accountname>\<server>\<character>\SavedVariables\`

The first is general settings, the second is individual settings per character, and relating to each characters individual trinkets.
Do it on one character first and see if it made any difference.


The addon hasn't been updated for the latest two versions of wow classic, but nothing has changed in the API as far as I know, so loading out of date addons should be just fine (or me just updating the the TOC version :P).

Hope this helps.
Let me know if any of this makes it work, or if it's still problematic.

**Edit:**
Looking through the code, there is a hard-coded limit of 30 trinkets. This limit is easy to increase, but that doesn't seem to be the issue in your case.

**Comment by VictAlucard** [comment]
I've tried placing trinkets in bank, deleting the entire folder, I've not done a data purge yet by removing those specific lua files. I will update once that's done. Thanks for the prompt reply!

The purge solved the issue. I had to remove the addon as well as remove all data, otherwise it would restore. Thanks!! I can share this with some others that have had this issue as well.

It seems now that the auto-queuer isn't working? I was able to Feign and it worked flawlessly. since the data purge it seems inactive. any other thoughts?  I suspect its something dealing with the "Stop Queue On Swap" option.

**Comment by Nixxen** [comment]
Hold up, the auto-queue was working for you earlier?
That never worked for me in the classic version.
If purging the data broke it, that could mean the data was from an earlier version, or some setting is messing with the auto queue (a setting that is on or off by default).

If you know others that have the same issue, but also have a working auto-queue, ask them to make a copy of their trinketmenu.lua from their savedvariables folders. Would be interesting to compare them just to see if there are any obvious errors there.

**Comment by VictAlucard** [comment]
[TrinketMenu.zip](https://github.com/Nixxen/TrinketMenu/files/4395015/TrinketMenu.zip)

I belive the original one i've used was Joev

https://github.com/joev/TrinketMenu_Classic/tree/master/TrinketMenu

If they're in my recycle bin :-D
as I usually shift-delete.
There is an author tha made a diff one.

I will continue testing. I would easily trade the auto-queue back to having that other issue.

I've read about this on a forum?
Figured out how to get it working, for some reason the Queue won't work without "Notify When Ready" or "Notify at 30 sec" enabled.
Changes needed in TrinketMenuQueue.lua:

UnitCastingInfo("player") -> CastingInfo()
UnitAura("player",buff) -> AuraUtil.FindAuraByName(buff,"player")

The moment I enabled "Notify at 30 sec" things are working as I expected them to. (also works with "Notify When Ready")

I hope these findings help with improving the addon as I'm super happy this thing exists.

Last thing, there is some conflict with the Stop quque on swap option when the notify option is enabled, I have itemrack enabled to sub in carrot trinket when I'm mounted, but trinket menu continuously tries to replace it, so I have to manually disable the auto queu when mounted, not a HUGE deal but just thought I'd bring to your attention.

**Comment by Nixxen** [comment]
Oh you absolute legend!
Thank you for that.
I'll get the changes made and test it for the raid tonight and see how it pans out during raid tonight.

Edit:
Turns out the API from the Joev version is very outdated. It uses some API that's deprecated in classic API.
I'll need to do some prodding at the code and see if I can figure out why the changes to the API have broken it (if that is the case).

Edit2: 
Found the issue. It basically encapsulates the function that updates the autoqueue check inside the timer for the notify system.
It's... Stupid.
Will see if I can solve it by either injecting it in another timer or just make a new timer specifically for the auto queue.

**Comment by Nixxen** [comment]
Think this should be solved now.
I also updated the addon interface version to the current one.
Give it a spin and let me know if you find any issues with it.

**Comment by VictAlucard** [comment]
Should I do a data purge before trying?

**Comment by VictAlucard** [comment]
I may be mistaken, but it seems to respond (swap)faster.

**Comment by Nixxen** [comment]
Closing issue. Problem solved.
