### ISSUE TITLE
No Menu Visible

### ISSUE THREAD

**Issue by rebz** [Nixxen/TrinketMenu#7]
Disabled all addons except Trinket Menu.

I do not see the 2 trinket slots in the UI and the menu does not show any values.

![image](https://user-images.githubusercontent.com/628385/81424171-89342400-9123-11ea-975f-02b614dc70dc.png)

**Comment by rebz** [comment]
The `/trinket` or `/trinketmenu` commaand was not working either.

I re-enabled all my addons, when doing so `/trinket` was working again. I then typed `/trinketmenu reset` and it fixed the displaay.

**Comment by rebz** [comment]
Feel free to close this or look further into it.

**Comment by Nixxen** [comment]
Heya Rebz.

I'll close this, but out of curiosity - Was this the only trinket menu version you had used, or did you also download or test some other versions?

I've had cases where people used older versions and the data saved between the versions was incompatible causing strange issues similar to this.

**Comment by Nixxen** [comment]
Fixed through adding missing libstub library.
Thanks to @pnx
