### ISSUE TITLE
Release for WOW classic on Twitch

### ISSUE THREAD

**Issue by sh977218** [Nixxen/TrinketMenu#8]
It would be nice to have this addon to be on Twitch for WOW classic.

**Comment by Nixxen** [comment]
I don't have access to the TrinketMenu project on curse/twitch (it's been abandoned some years ago, which is why I fixed it for classic).
I could apply for a new project with a similar name I suppose.
I'll give it a shot and see if curse admins accept it.

**Comment by Nixxen** [comment]
Curse admins require authorization from Gello3 to upload to the curse network (Twitch being among the network).
Gello3 is active on curse, so I sent him a message a few days back.
So far I have not yet heard from him.
Unless he gives explicit permission this can't be hosted on curse, sadly.

**Comment by sh977218** [comment]
If he doesn’t reply, either allow or deny, can you release this add-on on curse under a different name?

**Comment by Nixxen** [comment]
Hehe, that would kind of be dodging the issue :P
I'd like to keep my nose clean with twitch, so I'll have to wait for his acceptance before resubmitting the project.
